// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgakecslbjamltjdllcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nYWtlY3NsYmphbWx0amRsbGNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0OTcyODQsImV4cCI6MjA2MTA3MzI4NH0.WZgD2VkzQreC4m1BoDlXKwb091L_rKIJaeX5gmqu_-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);